### PR TITLE
Support for Symfony 3

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Comment by pies** [comment]
This patch makes my #103 redundant.

**Comment by pies** [comment]
@kubawerlos Please fix conflicts.

**Comment by kubawerlos** [comment]
@pies what about removing composer.lock? It is library after all.

**Comment by pies** [comment]
@kubawerlos That's a great point, can you please delete it? :) Sorry about making you jump trough hoops.

**Comment by kubawerlos** [comment]
@pies it's done.

**Comment by pies** [comment]
@kubawerlos Thank you.

**Pull request merged**
