### PR TITLE
[1.2.0] Features from #68

### PR DESCRIPTION
**Pull request by cozylife**
This pull request finishes issue #68.

### CODE REVIEW

**Comment by CozyLife** [comment]
Any idea on when you'll have time to merge this pull request? Is there something I can do to speed it along?

**Comment by CozyLife** [comment]
Did you go on vacation, Alec, or are you just really really busy? :P

**Comment by alecsammon** [comment]
Sorry - been on holiday. Lot's to catch up with - will try and get onto this asap

**Comment by CozyLife** [comment]
I'm glad to hear you're not dead. Haha! Nice to have you back, man.

**Comment by CozyLife** [comment]
So, any news on when you'll start the merging? I don't mean to be pushy, but the script is currently blocking my ability to easily update my software.

**Comment by alecsammon** [comment]
Hi Rick,

Sorry - been really crazy busy here. 

I'm not sure if this should be part of this library. Unless I'm still confused this seams to be a specific problem with your implementation - and shouldn't be part of the library. Although it makes your implementation easier - it's not appropriate for other people using the library.

I can't see why not merging security schemas is any different from not merging any part of the schema. 

I'm very happy to be convinced otherwise - I just don't want this library becoming too niche and preventing other people from easily adopting it.

**Comment by alecsammon** [comment]
Also - can you not just change your composer.json to point at your fork - shouldn't then matter if it take me a while to get updates merged in.

**Comment by CozyLife** [comment]
Let's take a bubble. The RAML spec states that [OAuth 1.0 and 2.0](http://raml.org/spec.html#oauth-1-0) are natively supported. Even the spec shows that they can have multiple URIs. Those URIs do NOT use custom data from the call. They are simply there to request tokens. If you post a new Twitter message to [Twitter's Request Token URI](https://api.twitter.com/oauth/request_token), then you'll get some weird results, especially if the authentication data gets overwritten by the request data from the main request. (Thus voiding either the main request's data integrity or the token request data's integrity.)

Compounding matters further, when you go to post the request token for authorization, you'll spam the authorization server with data from the main request, which again can overwrite the main request data. When you finally have your access token, and you send your main request, then you'll also post request token data, and authorization data off to the main request which could show very different results from what you'd expect.

The problem isn't just an extra "Authorization" header, but also the fact that OAuth supports posting data in the body for authentication, or authenticating through query parameters. There's a lot more bloat there when you make each call, plus the server may not understand what you're trying to do. (Are you requesting a token, trying to authorize a token, or make a request with the access token?) What should the server do if for some reason the request contains authorization data in the query, headers, AND the body?

I could go on all day about how wrong it is to merge multiple requests into a unified data set, but I think you get the point.

**Comment by CozyLife** [comment]
Hi! I'm a pull request. Pull me. :)

**Comment by alecsammon** [comment]
I'm sorry for the delay on this. I've had no time recently to work on it.

I've still got a major concern with this. It looks like it's very specific to your use case, and I'm not sure if it's a great strategy to start having such customisations here. The library is already pretty complex!

You've spoken about not merging security schemas by default in v2, however this seams backwards to me. The point of this library is to take a RAML file and generate a PHP representation of it, if you don't want it in the PHP representation, then you shouldn't provide it in the RAML.

I'm really not sure on the best way to proceed - I don't know what's best for the library.

**Comment by CozyLife** [comment]
Alright, well I don't think there's any way to make my thoughts clearer, so I think I'll just keep working on my branch of the project when I can. For those who come across this thread and do not wish to have their main request combined with that of the separate [OAuth 1.0a](http://oauth.net/core/1.0a/#anchor9) or [OAuth 2.0](http://tools.ietf.org/html/rfc6749#section-4) calls as per the spec, or find that they need to make multiple authentication calls for OpenID or the like, check out [my branch](https://github.com/CozyLife/php-raml-parser).

**Comment by alecsammon** [comment]
Right....

Firstly an apology- I think it's me that's not made my thoughts clear (probably because they weren't clear in the first place!)

There are two separate concerns mixed up here.

1) The library should correctly merge security schemas.
2) The option of merging security schemas should be optional.

I definitely agree that the first point is essential. This should have already been supported, and was just my laziness that prevented it from being written by me. I've split just this portion of your work into a separate pull request (along with some refactoring, because I just can't help myself!). This work isn't quite completed - I need to compare the diff between your branches and mine - but you can see it here: #79 

Regarding the second point, I was failing to see why this library should support that feature. I was also concerned about the Parser class getting more and more complex. I was concerned that if we started introducing flags to the parse method, then the method would quickly become too complicated. However - I don understand that as a major user of this library you should have significant input into the direction of the project.

A good compromise could be the creation of a ParserSettings object. This would allow easy extension in the future, should support what you need, and prevents the main Parser class getting much more complicated. This pull request still needs some more work, but wanted your feedback first. It's available here: #78

**Comment by cozylife** [comment]
I agree that a separate configuration object is a smart idea to keep the code clean. As for merging the security objects, as long as I can have custom settings for OAuth objects (not just RAML specified required settings), and the multiple OAuth calls are not merged into one (or I have the option of not merging them) then I'm fine with it.

**OAuth 1.0a**

1. Make a call to [request an unauthorized token](http://oauth.net/core/1.0a/#auth_step1).
2. ([User authorizes the token](http://oauth.net/core/1.0a/#auth_step2))
3. Make a call to [grab the access token](http://oauth.net/core/1.0a/#auth_step3).
4. Make the [main call](http://oauth.net/core/1.0a/#anchor12) with the authorized token.

Those three calls need to have their own request format, and cannot reliably be merged.

**OAuth 2.0**

1. Make a call to request the authorization token. (Or refresh the token)
2. Make the main call.

Those also cannot be reliably merged. Notice the "access token request" and "authorization token request" sections for the different calls in the [OAuth 2.0 spec](http://tools.ietf.org/html/rfc6749).

**Comment by martin-georgiev** [comment]
This PR is outdated and the original author (@cozylife) says he's ending his engineering career. I'm closing the PR for now, it can be reopened later if needed.

**Pull request closed without merging**
