### PR TITLE
V3.0

### PR DESCRIPTION
**Pull request by InfopactMLoos**
I have done a first implementation of types and their validations. Please review the changes and create a new branch (v3.0?) for this request, as was discussed in [Issue 108](https://github.com/alecsammon/php-raml-parser/issues/108). It is a working in progress for the entire 1.0 specification but for my use case it already works. I have made a quick shortlist of things we should add for a complete 1.0 release in the README. Also we can probably use more unit tests. 

Also @AnzeDspot, @therealgambo

### CODE REVIEW

**Comment by therealgambo** [comment]
@InfopactMLoos , Sorry for the late reply. I'll have a look at this hopefully within the next day or so.

As for whether this eventually gets merged, I'm unsure as it looks like @alecsammon is rather inactive at the moment. I'll be happy to install directly from your fork, assuming it is tagged correctly and won't go away anytime soon :)

**Comment by goodevilgenius** [comment]
What's the status of this? I'd like to use this library, but I'm only use RAML 1.0.

This PR was opened over a year ago, and there's been no update on this at all.

**Comment by therealgambo** [comment]
I don't think anything is being merged at the moment. You should read over this issue: https://github.com/alecsammon/php-raml-parser/issues/117

The eLama fork is more inline with the 1.0 spec than this.

**Comment by martin-georgiev** [comment]
The @eLama 's fork with RAML 1.0 support is now backported to `master`. There is a new version ([3.0.0](https://github.com/alecsammon/php-raml-parser/releases/tag/3.0.0)) release that contains it so please do let me know if you run into any issues with it.

**Pull request closed without merging**
