### PR TITLE
Feature #59, and all bug fixes from #58

### PR DESCRIPTION
**Pull request by CozyLife**
I don't know how the last pull request got closed, but here's the new one with even more magic from #55, #56, #57, and #59.

### CODE REVIEW

**Comment by brendo** [comment]
This work is great and very helpful for the project, but are you able to add (or correct) tests to prevent these issues from creeping into the codebase again? The CI indicates these changes have broken a couple of existing test cases.

**Comment by alecsammon** [comment]
Hi All,

Sorry been a bit quiet recently. I'm looking into the tests for this pull request, will update it in a couple of hours.

**Comment by alecsammon** [comment]
Ok, I've got the tests passing now.

Quick question for @CozyLife, @brendo, plus anyone else watching.

The LFI directory traversal security fix is a backwards incompatible change, it breaks my companies usage of the parser. As a result we need a way of enabling/disabling the check.

So - should this feature be enabled by default (and introduce a breaking change), or should it be disabled by default (but potentially open up a security issue)

**Comment by brendo** [comment]
> The LFI directory traversal security fix is a backwards incompatible change, it breaks my companies usage of the parser. As a result we need a way of enabling/disabling the check.

Likewise, we had all RAML's in one folder and all schemas in another folder :)

> So - should this feature be enabled by default (and introduce a breaking change), or should it be disabled by default (but potentially open up a security issue)

The first would have to be done with a `2.0.x` release, the later could be done as a `1.1.x` release. Your call, I'd perhaps lean with first, even though it's a shame because we just hit `1.0.0`.

**Comment by CozyLife** [comment]
I suggest making it backwards compatible in 1.x, but having it enabled by default in 2.x. I don't know your situation at your companies, but if your Yaml code is user editable, you might consider migrating to the more secure version.

**Comment by brendo** [comment]
> I suggest making it backwards compatible in 1.x, but having it enabled by default in 2.x.

This is a good solution!

> I don't know your situation at your companies, but if your Yaml code is user editable, you might consider migrating to the more secure version.

Fortunately not, it's hand written by the API designer and given to the developers for implementation.

**Comment by alecsammon** [comment]
Great - that was my preferred solution :)

Want to write a couple of tests after work, give me 12 hours or so.

**Comment by alecsammon** [comment]
two new methods on `\Raml\Parser`

`->allowDirectoryTraversal()`
`->preventDirectoryTraversal()`

By default it is enabled. In v2 we will set it to be disabled by default.

If you are happy I will tag as v1.1.0

**Comment by CozyLife** [comment]
Looks good to me.

**Pull request merged**
