### PR TITLE
[1.3.0] Features from issue #71

### PR DESCRIPTION
**Pull request by cozylife**
See issue #71.

### CODE REVIEW

**Comment by CozyLife** [comment]
So, the moral of the story is to always reset an array before using key(). It's actually good practice to do that instead of counting on where I think PHP's internal pointer is at.

**Comment by CozyLife** [comment]
Hi. I'm a month old pull request. Pull me! :)

**Comment by martin-georgiev** [comment]
@cozylife, will you be able to backmerge `master` and resolve the conflicts here?

**Comment by martin-georgiev** [comment]
Closing this one due to changes' age, merge conflicts and @cozylife says he's no longer an active software developer.

**Pull request closed without merging**
