### PR TITLE
I've fixed issues 55, 56, and 57 which I opened.

### PR DESCRIPTION
**Pull request by CozyLife**
Please merge in my changes to your repo.

### CODE REVIEW

**Comment by CozyLife** [comment]
I'm not sure what happened, but Travis CI is having issues with Git clone.

**Comment by alecsammon** [comment]
Yeah - think github are having some major DDOS problems at the moment.

Thanks for the pull requests - will review and get them merged ASAP

**Comment by CozyLife** [comment]
That would explain a lot. Thanks for the heads up!

**Comment by Toflar** [comment]
This is not at all a security fix. A simple string replacement on `../` is **not** how you fix directory traversal issues. I can pass in `....//` which would result in in `../` again, so it's very, very easy to hack. You need to normalize the paths which is also described in [RFC 3986](https://tools.ietf.org/html/rfc3986). But in this case a simple `realpath()` is exactly what you're looking for :)

**Comment by CozyLife** [comment]
That's true. It was a rush job since I didn't personally need it and I didn't feel like testing it, so I went with something too simple. Now I look foolish for being lazy. :)

Also, hold of on the pull request. I think I have one more thing to add to it later today.

**Comment by CozyLife** [comment]
Alright. It's ready when you are.

**Pull request closed without merging**
